### ISSUE TITLE
App with id zimbradrive has invalid signature

### ISSUE THREAD

**Issue by travisph** [ZeXtras/zimbra-drive#11]
NextCloud 11.0.5
Fedora 26 Server
PHP 7.1.9

    Error | core | App with id zimbradrive has invalid signature

Seems to be a common issue on version 11.0.5 for the zimbradrive app.

**Comment by bud-mo** [comment]
Hello @travisph We have reviewed the signing process. Please dowload the new version form the [store](https://apps.nextcloud.com/apps/zimbradrive), I will close this issue on Your confirmation.
