### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by jamesh76** [ZeXtras/zimbra-drive#18]
The version in the app store 0.8.15 fails to install with a "app with id zimbradrive has invalid signature" error.  Nextcloud 12.04, existing zimbradrive app version 0.8.10.  I assumed this was because someone neglected to update the signature, so I downloaded the .tgz and attempted to install it manually as I've done several times in the past, but this time that causes Nextcloud to fail completely.  I did notice that the versioning in the "info.xml" shows 0.8.16

**Comment by ZxUgoPadoan** [comment]
Hello @jamesh76 and thank you for the issue report.
Can you send to ext.services@zextras.com the Nextcloud log file?

**Comment by jamesh76** [comment]
Hello @ZxUgoPadoan and thank you for responding. The current version in the app store "0.8.18" does not appear to have this problem. I was able to install it on both of my servers without any issues. If you still need the logs, I will be happy to find my previous attempts. 

Thanks, 
James

**Comment by bud-mo** [comment]
I close
