### ISSUE TITLE
App config not saved using Firefox

### ISSUE THREAD

**Issue by Tuxem** [ZeXtras/zimbra-drive#19]
When using Firefox (58) to modify app configuration, nothing is saved.

Using Chrome/Chromium it works.

**Comment by ZxUgoPadoan** [comment]
Hello @Tuxem and thank you for the issue report.
The bug should be fixed in the new release (v. 0.8.18), let me know if the problem persists.

**Comment by Tuxem** [comment]
Hi @ZxUgoPadoan, I just tested it and it works on Firefox 58.

Thanks !
