### ISSUE TITLE
Drive tab can't be accessed if NC user has a failed external storage

### ISSUE THREAD

**Issue by Emi94** [ZeXtras/zimbra-drive#27]
If the user on Nextcloud has an external storage mounted with the External Storages app and it fails, when trying to access the Zimbra Drive tab, it throws this error:
![screenshot from 2018-04-16 12-04-49](https://user-images.githubusercontent.com/11816318/38800006-b9f41818-416e-11e8-93b6-70b495404e33.png)
And the Drive tab doesn't even open.

You might want to check for such cases and if an external storage can't be accessed simply exclude it so access to the other files would still be possible.

**Comment by ZxUgoPadoan** [comment]
Zimbra Drive is an official Zimbra product - support is provided through the official Zimbra channels to both Open Source and Network Edition customers.

**Comment by Emi94** [comment]
I don't need support, I posted an issue that this app has and provided an idea how it could be solved.
