### ISSUE TITLE
zimbradrive breaks nextcloud

### ISSUE THREAD

**Issue by fgasparuk** [ZeXtras/zimbra-drive#3]
I have a brand new installation of nextcloud on Centos 7 from repository.  Everything seems to be working OK.  I downloaded the zimbradrive app to interact with zimbra.
As soon as I move the zimbradrive directory into the /usr/share/nextcloud/apps/ nextcloud stops working.  The logs throw this error
{PHP} syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at /usr/share/nextcloud/apps/zimbradrive/appinfo/app.php#63

If I comment the lines 63 to 65 then next cloud starts working again, but when going to test the connection to zimbra under admin, it crashes again.  I haven't got a clue what these 3 lines do, I was just trying to see if at least I could access nextcloud again, and I can.  Maybe I've got some dependency missing, any help would be appreciated.
Thanks,
Federico

**Comment by bud-mo** [comment]
Hello @fgasparuk and thank you for the issue report!
Which version of nextcloud are you running?

**Comment by fgasparuk** [comment]
Hi, 

Thanks for your response. I installed if from Centos packages and these are the versions 

nextcloud.noarch 10.0.4-2.el7 @epel 
nextcloud-httpd.noarch 10.0.4-2.el7 @epel 
nextcloud-mysql.noarch 10.0.4-2.el7 @epel 

Regards, 
Federico 

	
Federico Gasparrini 
Nixe Limited 
10 th Floor, Citypoint, 1 Ropemaker Street, London EC2Y 9HT, United Kingdom 
Phone: +44 (0) 20 8370 7900 
Fax: +44 (0) 20 8370 7901 
Mobile: +44 (0) 780 879 2525 
Web: [ http://www.nixe.co.uk/ | http://www.nixe.co.uk ] 

Nixe s.r.l. 
Pte. Luis Saenz Pena 366 4 "A", Buenos Aires, (1110), Argentina 
Phone/Fax: +54 (0) 11 4383 7831 Ext.: 3002 

Nixe Limited - Registered Office: 7 Bideford Gardens, Enfield EN1 2RP, United kingdom - Registered in England No. 3913108

**Comment by bud-mo** [comment]
I suspect is an issue related to PHP, which version of PHP is running on the server?

**Comment by fgasparuk** [comment]
PHP 5.4.16 (cli) (built: Nov 6 2016 00:29:02) 
Copyright (c) 1997-2013 The PHP Group 
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies 


Again, the one from the centos repository. I tried not to change any versions to avoid problems. 

	
Federico Gasparrini 
Nixe Limited 
10 th Floor, Citypoint, 1 Ropemaker Street, London EC2Y 9HT, United Kingdom 
Phone: +44 (0) 20 8370 7900 
Fax: +44 (0) 20 8370 7901 
Mobile: +44 (0) 780 879 2525 
Web: [ http://www.nixe.co.uk/ | http://www.nixe.co.uk ] 

Nixe s.r.l. 
Pte. Luis Saenz Pena 366 4 "A", Buenos Aires, (1110), Argentina 
Phone/Fax: +54 (0) 11 4383 7831 Ext.: 3002 

Nixe Limited - Registered Office: 7 Bideford Gardens, Enfield EN1 2RP, United kingdom - Registered in England No. 3913108

**Comment by bud-mo** [comment]
@fgasparuk We are investigating on it, I will keep you updated as soon as I have more information.

**Comment by fgasparuk** [comment]
Thanks. Please let me know if you need me to run any tests or to send you any logs. 

Regards, 
Federico 

	
Federico Gasparrini 
Nixe Limited 
10 th Floor, Citypoint, 1 Ropemaker Street, London EC2Y 9HT, United Kingdom 
Phone: +44 (0) 20 8370 7900 
Fax: +44 (0) 20 8370 7901 
Mobile: +44 (0) 780 879 2525 
Web: [ http://www.nixe.co.uk/ | http://www.nixe.co.uk ] 

Nixe s.r.l. 
Pte. Luis Saenz Pena 366 4 "A", Buenos Aires, (1110), Argentina 
Phone/Fax: +54 (0) 11 4383 7831 Ext.: 3002 

Nixe Limited - Registered Office: 7 Bideford Gardens, Enfield EN1 2RP, United kingdom - Registered in England No. 3913108

**Comment by bud-mo** [comment]
Hello @fgasparuk We have updated the nextcloud app in the [store](https://apps.nextcloud.com/apps/zimbradrive), please update it and let us know if this issue can be closed ;)

**Comment by fgasparuk** [comment]
Hi Michele, 

As soon as I can I'll update it and let you know the result. I'm a bit busy at the moment so it might take me a week or two. 
Thank you very much. 
Federico 

	
Federico Gasparrini 
Nixe Limited 
10 th Floor, Citypoint, 1 Ropemaker Street, London EC2Y 9HT, United Kingdom 
Phone: +44 (0) 20 8370 7900 
Fax: +44 (0) 20 8370 7901 
Mobile: +44 (0) 780 879 2525 
Web: [ http://www.nixe.co.uk/ | http://www.nixe.co.uk ] 

Nixe s.r.l. 
Pte. Luis Saenz Pena 366 4 "A", Buenos Aires, (1110), Argentina 
Phone/Fax: +54 (0) 11 4383 7831 Ext.: 3002 

Nixe Limited - Registered Office: 7 Bideford Gardens, Enfield EN1 2RP, United kingdom - Registered in England No. 3913108
