### ISSUE TITLE
Zimbra drive Plugin compatibility with owncloud v10

### ISSUE THREAD

**Issue by mrveiss** [ZeXtras/zimbra-drive#4]
when could be expected the working plugin with v10 owncloud, php7 ?  i am willing to contribute testing time, as i am willing to authenticate my users against zimbra.

**Comment by bud-mo** [comment]
Hello @mrveiss,
We are testing the support for ownCloud 10 right now.
I will keep You in the loop ;)

**Comment by mrveiss** [comment]
Is there any chance that i could get my gands on?

**Comment by bud-mo** [comment]
Hello @mrveiss, **in a testing environment** feel tree to download and install the owncloud/nextcloud app from the main branch.
