### ISSUE TITLE
It is an obligation

### ISSUE THREAD

**Issue by MisterM74** [ZeXtras/zimbra-drive#5]
Hello
After installing the network version of Zimbra, I realize that Zextras is working with Zimbra (Zimbra drive).
Super, my question, you have to install Owcloud / NextCloud absolutely, or we can choose, one or the other ...
Yours sincerely
Mz

**Comment by bud-mo** [comment]
Hello @MisterM74!
Zimbra drive is an independent extension from ZeXtras and Zimbra network edition.
It can work with both owncloud OR nextcloud, You can choose one of Your favourite *cloud server.

Have a nice day
