### ISSUE TITLE
App with id zimbradrive has invalid signature

### ISSUE THREAD

**Issue by whelpton** [ZeXtras/zimbra-drive#6]
Hey guys, I'm trying to install on NextCloud & I'm getting an invalid signature error

**Comment by bud-mo** [comment]
Hello @whelpton please can You share more informations?
- version of Zimbra is running on Your server
- version of NextCloud is running on Your server
- version of the extension you are trying to install

**Comment by whelpton** [comment]
Nextcloud 11.0.2 (stable)
Extension: 0.8.12

I'm trying to install the extension directly through the apps page as well as manually, both ways are giving me invalid signature errors

**Comment by bud-mo** [comment]
Hello @travisph please follow the issue #11
