### ISSUE TITLE
Nextcloud12 app compatibility

### ISSUE THREAD

**Issue by maxxer** [ZeXtras/zimbra-drive#7]
https://apps.nextcloud.com/apps/zimbradrive

**Comment by 2beFlo** [comment]
Nexcloud 12 compatibility would be great!

**Comment by bud-mo** [comment]
Hello @maxxer and @2beFlo,
We have added the support to Nextcloud 12 in the new release available on the [store](https://apps.nextcloud.com/apps/zimbradrive) ;)
